# Generated by Django 4.2.11 on 2024-07-04 22:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from django.contrib.auth.models import Group, User
from rest_framework.authtoken.models import Token
from app_comm_api.models import MessageType, MessageState
from decouple import config

# Populate the database with initial data
def populate_db(apps, schema_editor):

    # Create a superuser
    user = User.objects.create_superuser(
        username=config('SUPERUSER_USERNAME'),
        email=config('SUPERUSER_EMAIL'),
        password=config('SUPERUSER_PASSWORD'),
        first_name=config('SUPERUSER_FIRST_NAME'),
        last_name=config('SUPERUSER_LAST_NAME'),
        last_login=timezone.now()
    )

    # Create message types
    msg_types = [
        MessageType(message_type_name="SOS"),
        MessageType(message_type_name="Needs"),
        MessageType(message_type_name="Problems")
    ]
    MessageType.objects.bulk_create(msg_types)

    # Create message states
    msg_states = [
        MessageState(message_state_name="Open"),
        MessageState(message_state_name="Closed"),
    ]
    MessageState.objects.bulk_create(msg_states)
    
    # Create groups
    groups = [
        Group(name="Nurse"),
        Group(name="Patient")
    ]
    Group.objects.bulk_create(groups)

    # Add user to a group
    group = Group.objects.get(name="Nurse")  # Retrieve the group by name
    user.groups.add(group)

    # Create a token for the new user
    Token.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0001_initial'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('authtoken', '0003_tokenproxy'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_info', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='level indicator')),
            ],
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_state_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=512)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_solution', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comm_api.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=6, max_digits=10)),
                ('y', models.DecimalField(decimal_places=6, max_digits=10)),
                ('imageWidth', models.DecimalField(decimal_places=6, max_digits=10)),
                ('imageHeight', models.DecimalField(decimal_places=6, max_digits=10)),
                ('radius', models.FloatField()),
                ('color', models.CharField(max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comm_api.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comm_api.messagestate'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comm_api.messagetype'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_db),
    ]
